/*
    SQL
*/

-- считать колличество всех записей в таблице
SELECT COUNT(*)
FROM invoice; 


SELECT
    billing_address,
    CAST(invoice_date AS date)
FROM invoice
WHERE total >= 8;


WHERE age > 43
  AND city IN ('Тула', 'Пермь');


SELECT email,
       fax
FROM client
WHERE fax IS NOT NULL
LIMIT 5;


-- получить уникальные значения по строкам
SELECT DISTINCT billing_country 
FROM invoice
LIMIT 5;


SELECT COUNT(DISTINCT billing_country)
FROM invoice;


-- общая выручка, количество заказов, средняя выручка для каждого города
SELECT billing_city,
    SUM(total),
    AVG(total),
    COUNT(*)
FROM invoice
WHERE billing_country = 'USA'
GROUP BY billing_city;


-- сортировка топ-5 городов по значению средней выручки
SELECT billing_city,
       AVG(total)
FROM invoice
WHERE billing_country = 'USA'
GROUP BY billing_city
ORDER BY AVG(total) DESC
LIMIT 5;


-- объединение двух таблиц по ключам
SELECT  c.first_name,
        c.last_name,
        EXTRACT(YEAR FROM CAST(invoice_date AS date)),
        MIN(i.total) AS min_cost,
        MAX(i.total) AS max_cost,
        ROUND(AVG(i.total), 2) AS average_cost,
        COUNT(i.total) AS total_purchases
FROM invoice AS i
INNER JOIN client AS c ON i.customer_id = c.customer_id
WHERE i.billing_country = 'USA'
GROUP BY first_name, last_name
ORDER BY average_cost DESC
LIMIT 10;


-- объединение таблиц по одинаковым значениям
SELECT a.actor_id,
       a.first_name,
       c.first_name
FROM actor AS a
FULL OUTER JOIN client AS c ON a.last_name = c.last_name
LIMIT 10;


-- подзапросы FROM
SELECT AVG(best_rating.average_rental)
FROM (SELECT
        m.rating,
        AVG(m.rental_rate) AS average_rental
    FROM movie AS m
    GROUP BY m.rating
    ORDER BY average_rental DESC
    LIMIT 5) AS best_rating;


-- подзапросы WHERE
SELECT *
FROM client
WHERE customer_id IN (SELECT customer_id
                      FROM invoice
                      GROUP BY customer_id
                      ORDER BY SUM(total) DESC
                      LIMIT 10);



-- создание новой таблицы в схеме
CREATE TABLE films (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title varchar(40) NOT NULL,
        produced integer NOT NULL,
        date_prod date,
        kind varchar(10),
        len_min integer
);

